### ISSUE TITLE
 improvements

### ISSUE THREAD

**Issue by dayanare** [Adalab/modulo-2-evaluacion-intermedia-SandraFernandz#1]
Some improvements

Really cool job @SandraFernandz  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Extract the feedback painter to a function.

### JavaScript: advanced

- [x] You are writing many times `"hint.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'hint'`?
 
### Good practices

- [x] Remove unnecessary commented code.

### HTML

- [x] Use placeholder.
- [x] Don't add an empty attribute for no special reason: by adding an empty `value` attribute we are indeed setting it to a certain (empty) value, do we want to do that?

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by SandraFernandz** [comment]
Hello, Dayana! Thank you for pointing out all improvements that can be made in this exercise. I have implemented most of them. Regarding 2 of the open issues, I have a question that I sent you in a private message. I am very much looking forward to receiving your answer in order to solve all issues and learn what I had missed! Kind regards
